# Generated by Django 2.1 on 2019-08-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190721_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='avatar',
            field=models.ImageField(blank=True, max_length=1000, upload_to='static/images/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='avatar',
            field=models.ImageField(blank=True, max_length=1000, upload_to='static/images/'),
        ),
    ]
