version: '3.7'

services:
    nginx:
        image: nginx
        container_name: "nginx"
        build: ./nginx
        ports:
            - "80:80"
        depends_on:
            - frontend

    frontend:
        image: node
        container_name: "frontend"
        build: ./frontend
        ports:
            - "4200"
        depends_on:
            - api

    postgres:
        container_name: "postgresql"
        image: postgres:12
        restart: always
        ports:
            - "5432"
        environment:
            POSTGRES_PASSWORD: Admin123!
            POSTGRES_USER: admin
            POSTGRES_DB: postgresql

    api:
        build: ./api
        container_name: "dpg_api"
        volumes:
            - ./api:/opt/docker_polls_group/api
        ports:
            - "8000"
        links:
            - postgres
        depends_on:
            - postgres
        command: gunicorn --reload wsgi:application -w 2 -b :8000 -t 120
